Check for gmake.
git-svn-id: https://axiom.svn.sourceforge.net/svnroot/axiom/branches/build-improvements@416 54bea96e-1511-0410-8851-aaeae44645fa

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1456,8 +1456,10 @@ axiom_build_sharedir=$axiom_builddir/share
 ## It is vital that noweb is present in the build environement.
 axiom_all_prerequisites=
 
-# Extract the first word of "make", so it can be a program name with args.
-set dummy make; ac_word=$2
+for ac_prog in gmake make
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_MAKE+set}" = set; then
@@ -1473,16 +1475,13 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_MAKE="make"
+    ac_cv_prog_MAKE="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  test -z "$ac_cv_prog_MAKE" && ac_cv_prog_MAKE="{ { echo "$as_me:$LINENO: error: 'make' program missing." >&5
-echo "$as_me: error: 'make' program missing." >&2;}
-   { (exit 1); exit 1; }; }"
 fi
 fi
 MAKE=$ac_cv_prog_MAKE
@@ -1493,6 +1492,12 @@ else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
+
+  test -n "$MAKE" && break
+done
+test -n "$MAKE" || MAKE="{ { echo "$as_me:$LINENO: error: Make utility missing." >&5
+echo "$as_me: error: Make utility missing." >&2;}
+   { (exit 1); exit 1; }; }"
 
 
 ## Make sure the C compiler is from GCC
