* configure.ac.pamphlet: Enfore GNU Make requirement.         * configure.ac: Regenerate.         * configure: Likewise.
git-svn-id: https://axiom.svn.sourceforge.net/svnroot/axiom/branches/build-improvements@433 54bea96e-1511-0410-8851-aaeae44645fa

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1456,7 +1456,10 @@ axiom_build_sharedir=$axiom_builddir/share
 ## It is vital that noweb is present in the build environement.
 axiom_all_prerequisites=
 
-for ac_prog in gmake make
+case $build in
+    *linux*)
+        # GNU/Linux systems come equipped with GNU Make, called `make'
+        for ac_prog in make
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -1499,6 +1502,59 @@ test -n "$MAKE" || MAKE="{ { echo "$as_me:$LINENO: error: Make utility missing."
 echo "$as_me: error: Make utility missing." >&2;}
    { (exit 1); exit 1; }; }"
 
+        ;;
+    *)
+        # Other systems tend to spell it `gmake' and such
+        for ac_prog in gmake make
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_MAKE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MAKE"; then
+  ac_cv_prog_MAKE="$MAKE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MAKE="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+MAKE=$ac_cv_prog_MAKE
+if test -n "$MAKE"; then
+  echo "$as_me:$LINENO: result: $MAKE" >&5
+echo "${ECHO_T}$MAKE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$MAKE" && break
+done
+test -n "$MAKE" || MAKE="{ { echo "$as_me:$LINENO: error: Make utility missing." >&5
+echo "$as_me: error: Make utility missing." >&2;}
+   { (exit 1); exit 1; }; }"
+
+        if !$MAKE --version | grep 'GNU' 2>/dev/null; then
+            { { echo "$as_me:$LINENO: error: Axiom build system needs GNU Make." >&5
+echo "$as_me: error: Axiom build system needs GNU Make." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+        ;;
+esac
 
 ## Make sure the C compiler is from GCC
 ac_ext=c
