Add preliminary support for SBCL, CLISP.  Now, src/boot can be build with GCL, SBCL, and CLISP.
git-svn-id: https://axiom.svn.sourceforge.net/svnroot/axiom/branches/build-improvements@445 54bea96e-1511-0410-8851-aaeae44645fa

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -664,6 +664,7 @@ INSTALL_SCRIPT
 INSTALL_DATA
 LN_S
 TOUCH
+MKTEMP
 AWK
 PATCH
 RANLIB
@@ -674,7 +675,11 @@ NOTANGLE
 NOWEAVE
 axiom_include_gcl
 AXIOM_LISP
+axiom_lisp_flavor
 axiom_gcl_rsym_hack
+axiom_quiet_flags
+axiom_eval_flags
+axiom_fasl_type
 axiom_all_prerequisites
 axiom_c_runtime
 CPP
@@ -3170,6 +3175,48 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+for ac_prog in mktemp
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_MKTEMP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MKTEMP"; then
+  ac_cv_prog_MKTEMP="$MKTEMP" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_MKTEMP="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+MKTEMP=$ac_cv_prog_MKTEMP
+if test -n "$MKTEMP"; then
+  { echo "$as_me:$LINENO: result: $MKTEMP" >&5
+echo "${ECHO_T}$MKTEMP" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$MKTEMP" && break
+done
+
 
 case $build in
      *-solaris9)
@@ -3697,6 +3744,7 @@ fi
 ##
 ## We will default to GCL later, if no lisp implementation is specified.
 axiom_lisp=
+axiom_lisp_flavor=unknown
 
 # Check whether --with-lisp was given.
 if test "${with_lisp+set}" = set; then
@@ -3782,7 +3830,8 @@ echo "$as_me: error: --disable-gcl specified but no GCL image found" >&2;}
        AXIOM_LISP='$(axiom_build_bindir)/gcl'
        axiom_all_prerequisites="$axiom_all_prerequisites all-gcl"
        axiom_include_gcl=yes
-       axiom_use_gcl=yes
+       axiom_lisp_flavor=gcl
+       axiom_fasl_type=o
        ;;
     yes,*)
        { { echo "$as_me:$LINENO: error: --with-lisp=$axiom_lisp conflicts with --enable-gcl" >&5
@@ -3790,22 +3839,93 @@ echo "$as_me: error: --with-lisp=$axiom_lisp conflicts with --enable-gcl" >&2;}
    { (exit 1); exit 1; }; }
        ;;
     *)
-       if $axiom_lisp --version | grep 'GNU' 2>/dev/null; then
-           axiom_use_gcl=yes;
-       fi
+       ## As of this writting, the Lisp systems ECL, GCL, and SBCL all
+       ## understands the command line option --help, though they do
+       ## behave very differently.  Some of them just print out the
+       ## help information and exits.  Others, such as GCL, think they
+       ## must enter a read-eval-print loop (which isn't very helpful).
+       { echo "$as_me:$LINENO: checking which flavor of Lisp" >&5
+echo $ECHO_N "checking which flavor of Lisp... $ECHO_C" >&6; }
+       what=`echo '(quit)' | $axiom_lisp --help`
+       case $what in
+           *GCL*)
+               axiom_lisp_flavor=gcl
+               ;;
+           *ecl*)
+               axiom_lisp_flavor=ecl
+               ;;
+           *sbcl*)
+               axiom_lisp_flavor=sbcl
+               ;;
+           *CLISP*)
+               axiom_lisp_flavor=clisp
+               ;;
+       esac
+       { echo "$as_me:$LINENO: result: $axiom_lisp_flavor" >&5
+echo "${ECHO_T}$axiom_lisp_flavor" >&6; }
 esac
+
 
 ## The following is a horrible to arrange for GCL to successfully
 ## rebuild symbol tables with "rsym" on Windows platform.  It should
 ## go away as soon as GCL upstream is fixed.
-case $axiom_use_gcl,$target in
-    yes,*mingw*)
+case $axiom_lisp_flavor,$target in
+    gcl,*mingw*)
         axiom_gcl_rsym_hack='d=`echo "(format nil \"~a\" si::*system-directory*)" | $(AXIOM_LISP) | grep "/gcl.*/" | sed -e "s,\",,g"`; cp $$d/rsym$(EXEEXT) .'
         ;;
     *)
         axiom_gcl_rsym_hack=':'
         ;;
 esac
+
+## How are we supposed to tell the Lisp system to eval an expression
+## in batch mode?  What is the extension of a compiled Lisp file?
+case $axiom_lisp_flavor in
+    gcl)
+       axiom_quiet_flags='-batch'
+       axiom_eval_flags='-eval'
+       ;;
+    ecl)
+       axiom_quiet_flags=
+       axiom_eval_flags='-eval'
+       ;;
+    sbcl)
+       axiom_quiet_flags='--noinform --noprint'
+       axiom_eval_flags='--eval'
+       ;;
+    clisp)
+       axiom_quiet_flags='--quiet'
+       axiom_eval_flags='-x'
+       ;;
+    *) { { echo "$as_me:$LINENO: error: We do not know how to build Axiom this $axiom_lisp" >&5
+echo "$as_me: error: We do not know how to build Axiom this $axiom_lisp" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+
+
+if test -z $axiom_fasl_type; then
+    { echo "$as_me:$LINENO: checking compiled Lisp file extension" >&5
+echo $ECHO_N "checking compiled Lisp file extension... $ECHO_C" >&6; }
+    ## We set the IFS to <space> as we don't want automatic
+    ## replacement of <newline> by <space>.
+    axiom_save_IFS=$IFS
+    IFS=' '
+    axiom_fasl_type=`$axiom_lisp $axiom_quiet_flags $axiom_eval_flags '(progn (format t "axiom_fasl_type=~a" (pathname-type (compile-file-pathname "foo.lisp"))) (quit))'`
+
+    ## Now pull out the fasl type.  ECL has the habit of spitting noise
+    ## about internal loading.  Therefore, we must look only for a line that
+    ## begins with axiom_fasl_type.
+    axiom_fasl_type=`echo $axiom_fasl_type | grep '^axiom_fasl_type'`
+    IFS=$axiom_save_IFS
+    axiom_fasl_type=`echo $axiom_fasl_type | sed -e 's/axiom_fasl_type=//'`
+    if test -z $axiom_fasl_type; then
+        { { echo "$as_me:$LINENO: error: Could not determine extension for compiled Lisp files" >&5
+echo "$as_me: error: Could not determine extension for compiled Lisp files" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    { echo "$as_me:$LINENO: result: $axiom_fasl_type" >&5
+echo "${ECHO_T}$axiom_fasl_type" >&6; }
+fi
 
 
 
@@ -9137,6 +9257,7 @@ INSTALL_SCRIPT!$INSTALL_SCRIPT$ac_delim
 INSTALL_DATA!$INSTALL_DATA$ac_delim
 LN_S!$LN_S$ac_delim
 TOUCH!$TOUCH$ac_delim
+MKTEMP!$MKTEMP$ac_delim
 AWK!$AWK$ac_delim
 PATCH!$PATCH$ac_delim
 RANLIB!$RANLIB$ac_delim
@@ -9147,7 +9268,11 @@ NOTANGLE!$NOTANGLE$ac_delim
 NOWEAVE!$NOWEAVE$ac_delim
 axiom_include_gcl!$axiom_include_gcl$ac_delim
 AXIOM_LISP!$AXIOM_LISP$ac_delim
+axiom_lisp_flavor!$axiom_lisp_flavor$ac_delim
 axiom_gcl_rsym_hack!$axiom_gcl_rsym_hack$ac_delim
+axiom_quiet_flags!$axiom_quiet_flags$ac_delim
+axiom_eval_flags!$axiom_eval_flags$ac_delim
+axiom_fasl_type!$axiom_fasl_type$ac_delim
 axiom_all_prerequisites!$axiom_all_prerequisites$ac_delim
 axiom_c_runtime!$axiom_c_runtime$ac_delim
 CPP!$CPP$ac_delim
@@ -9165,12 +9290,9 @@ PLF!$PLF$ac_delim
 CCF!$CCF$ac_delim
 LDF!$LDF$ac_delim
 LISP!$LISP$ac_delim
-GCLOPTS!$GCLOPTS$ac_delim
-LIBOBJS!$LIBOBJS$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 95; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -9189,6 +9311,50 @@ fi
 
 cat >>$CONFIG_STATUS <<_ACEOF
 cat >"\$tmp/subs-1.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+GCLOPTS!$GCLOPTS$ac_delim
+LIBOBJS!$LIBOBJS$ac_delim
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 3; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-2.sed" <<\CEOF$ac_eof
 /@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
 _ACEOF
 sed '
@@ -9451,7 +9617,7 @@ s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
