Build process cleanups.
git-svn-id: https://axiom.svn.sourceforge.net/svnroot/axiom/branches/wh-sandbox@510 54bea96e-1511-0410-8851-aaeae44645fa

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6923,17 +6923,90 @@ fi
 ## Some part of Axiom depends on Xpm.  That library has kind uncertain
 ## future.  At some point in the past, it was deprecated, to be
 ## replaced by xpm-nox; then came back again.  So, its support may
-## vary from system to system.  For the moment, we assume that if X11
-## is found then, Xpm is already present.  Though, clearly that is a
-## very optimistic assumption.  Long term, Axiom should get rid of
-## dependence on Xpm.  A nearly fool-proof test would be probably
-## inspired by AC_PATH_XTRA.  I don't have time to get to that
-## complication right now.  Will fix later.
+## vary from system to system.  For the moment, we do a quick sanity
+## check and disable X11 if Xpm is not present.  Long term, Axiom should
+## get rid of dependence on Xpm.  Another possibility is to (optionally)
+## bundle Xpm source tarball and build Xpm if needed.
+
+if test -z $no_x; then
+  echo "$as_me:$LINENO: checking for XpmReadFileToImage in -lXpm" >&5
+echo $ECHO_N "checking for XpmReadFileToImage in -lXpm... $ECHO_C" >&6
+if test "${ac_cv_lib_Xpm_XpmReadFileToImage+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXpm $X_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XpmReadFileToImage ();
+int
+main ()
+{
+XpmReadFileToImage ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Xpm_XpmReadFileToImage=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Xpm_XpmReadFileToImage=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Xpm_XpmReadFileToImage" >&5
+echo "${ECHO_T}$ac_cv_lib_Xpm_XpmReadFileToImage" >&6
+if test $ac_cv_lib_Xpm_XpmReadFileToImage = yes; then
+  axiom_has_xpm=yes
+else
+  axiom_has_xpm=no
+fi
+
+else
+  axiom_has_xpm=no
+fi
+
 X_PRE_LIBS="-lXpm $X_PRE_LIBS"
 
 
 ## If the system supports X11, then build graphics and hyperdoc
-if test -z $no_x; then
+if test x"$axiom_has_xpm" = xyes; then
     axiom_c_runtime="$axiom_c_runtime graphics"
     axiom_src_all="$axiom_src_all all-graph"
     axiom_src_subdirs="$axiom_src_subdirs graph"
@@ -6954,7 +7027,7 @@ else
 echo "$as_me: The Gaphics and HyperDoc components are disabled." >&6;}
 fi
 
-if test -z $no_x; then
+if test x"$axiom_has_xpm" = xyes; then
    if test "${ac_cv_header_regex_h+set}" = set; then
   echo "$as_me:$LINENO: checking for regex.h" >&5
 echo $ECHO_N "checking for regex.h... $ECHO_C" >&6
