More cleanup work.  Fix thinko in the original build system.
git-svn-id: https://axiom.svn.sourceforge.net/svnroot/axiom/branches/build-improvements@152 54bea96e-1511-0410-8851-aaeae44645fa

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -274,7 +274,7 @@ PACKAGE_STRING='Axiom build improvements branch 2006-08-26'
 PACKAGE_BUGREPORT='axiom-developer@nongnu.org'
 
 ac_unique_file="src/Makefile.pamphlet"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS axiom_top_srcdir build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os axiom_builddir axiom_build_bindir axiom_build_libdir axiom_targetdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT axiom_cflags INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S AWK TAR PATCH MAKE RANLIB ac_ct_RANLIB AR TOUCH LATEX MAKEINDEX NOTANGLE NOWEAVE GCL axiom_required_build_utils CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS X_CLFAGS AXIOM PLF CCF LDF LISP GCLOPTS SRCDIRS axiom_build_notangle axiom_build_noweave LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS axiom_top_srcdir build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os axiom_builddir axiom_build_bindir axiom_build_libdir axiom_targetdir MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT axiom_cflags INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S TOUCH AWK TAR PATCH RANLIB ac_ct_RANLIB AR LATEX MAKEINDEX NOTANGLE NOWEAVE GCL axiom_required_build_utils CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS X_CLFAGS AXIOM PLF CCF LDF LISP GCLOPTS SRCDIRS axiom_build_notangle axiom_build_noweave LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1426,6 +1426,48 @@ echo "$as_me: error: Sorry, only native builds are currently supported" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+## Accumulate list of utils needed for the build platform
+axiom_required_build_utils=
+
+# Extract the first word of "make", so it can be a program name with args.
+set dummy make; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_MAKE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MAKE"; then
+  ac_cv_prog_MAKE="$MAKE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MAKE="make"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_MAKE" && ac_cv_prog_MAKE="{ { echo "$as_me:$LINENO: error: 'make' program missing." >&5
+echo "$as_me: error: 'make' program missing." >&2;}
+   { (exit 1); exit 1; }; }"
+fi
+fi
+MAKE=$ac_cv_prog_MAKE
+if test -n "$MAKE"; then
+  echo "$as_me:$LINENO: result: $MAKE" >&5
+echo "${ECHO_T}$MAKE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
 ## Make sure the C compiler is from GCC
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -2458,6 +2500,44 @@ else
 echo "${ECHO_T}no, using $LN_S" >&6
 fi
 
+# Extract the first word of "touch", so it can be a program name with args.
+set dummy touch; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_TOUCH+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$TOUCH"; then
+  ac_cv_prog_TOUCH="$TOUCH" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_TOUCH="touch"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_TOUCH" && ac_cv_prog_TOUCH="{ { echo "$as_me:$LINENO: error: 'touch' program is missing." >&5
+echo "$as_me: error: 'touch' program is missing." >&2;}
+   { (exit 1); exit 1; }; }"
+fi
+fi
+TOUCH=$ac_cv_prog_TOUCH
+if test -n "$TOUCH"; then
+  echo "$as_me:$LINENO: result: $TOUCH" >&5
+echo "${ECHO_T}$TOUCH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 
 case $build in
      *-solaris9)
@@ -2711,45 +2791,6 @@ echo "$as_me: error: Axiom needs a patch program" >&2;}
         ;;
 esac
 
-# Extract the first word of "make", so it can be a program name with args.
-set dummy make; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_MAKE+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$MAKE"; then
-  ac_cv_prog_MAKE="$MAKE" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_MAKE="make"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_prog_MAKE" && ac_cv_prog_MAKE="{ { echo "$as_me:$LINENO: error: 'make' program missing." >&5
-echo "$as_me: error: 'make' program missing." >&2;}
-   { (exit 1); exit 1; }; }"
-fi
-fi
-MAKE=$ac_cv_prog_MAKE
-if test -n "$MAKE"; then
-  echo "$as_me:$LINENO: result: $MAKE" >&5
-echo "${ECHO_T}$MAKE" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
@@ -2830,7 +2871,6 @@ else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
 
-
 # Extract the first word of "ar", so it can be a program name with args.
 set dummy ar; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -2864,45 +2904,6 @@ AR=$ac_cv_prog_AR
 if test -n "$AR"; then
   echo "$as_me:$LINENO: result: $AR" >&5
 echo "${ECHO_T}$AR" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-# Extract the first word of "touch", so it can be a program name with args.
-set dummy touch; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_TOUCH+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$TOUCH"; then
-  ac_cv_prog_TOUCH="$TOUCH" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_TOUCH="touch"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_prog_TOUCH" && ac_cv_prog_TOUCH="{ { echo "$as_me:$LINENO: error: 'touch' program is missing." >&5
-echo "$as_me: error: 'touch' program is missing." >&2;}
-   { (exit 1); exit 1; }; }"
-fi
-fi
-TOUCH=$ac_cv_prog_TOUCH
-if test -n "$TOUCH"; then
-  echo "$as_me:$LINENO: result: $TOUCH" >&5
-echo "${ECHO_T}$TOUCH" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -2985,9 +2986,6 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-
-## Accumulate list of utils needed for the build platform
-axiom_required_build_utils=
 
 ## -------------------------
 ## -- Which noweb to use? --
@@ -4827,68 +4825,8 @@ fi
 X_PRE_LIBS="-lXpm $X_PRE_LIBS"
 
 
-if test -f /etc/redhat-release; then
-   SYSNAME=`cat /etc/redhat-release`
-   if test "$SYSNAME" = "Fedora Core release 3 (Heidelberg)"; then
-       SYSNAME=fedora3
-   fi
-   { echo "$as_me:$LINENO: SYSNAME=$SYSNAME" >&5
-echo "$as_me: SYSNAME=$SYSNAME" >&6;}
-fi
-if test "$SYSNAME" != "fedora3"; then
-   SYSNAME=`uname -s`
-   { echo "$as_me:$LINENO: $SYSNAME" >&5
-echo "$as_me: $SYSNAME" >&6;}
-   case "$SYSNAME" in
-      Linux)
-         SYSNAME=linux ;;
-      MINGW32_NT-5.1)
-         SYSNAME=windows ;;
-      SunOS)
-         SYSNAME=solaris9 ;;
-      freebsd)
-         ;;
-      *)
-         SYSNAME=$target
-         { echo "$as_me:$LINENO: Your system name is $SYSNAME" >&5
-echo "$as_me: Your system name is $SYSNAME" >&6;}
-         { echo "$as_me:$LINENO: Building Axiom on this kind of system was not tried before" >&5
-echo "$as_me: Building Axiom on this kind of system was not tried before" >&6;}
-         { echo "$as_me:$LINENO: Send a note to axiom-developer@nongnu.org about it" >&5
-echo "$as_me: Send a note to axiom-developer@nongnu.org about it" >&6;}
-   esac
-fi
+AXIOM=`pwd`/mnt/$target
 
-must_set_AXIOM() {
-   case "$SYSNAME" in
-      freebsd)
-         { echo "$as_me:$LINENO: Note that freebsd usually has noweb available" >&5
-echo "$as_me: Note that freebsd usually has noweb available" >&6;}
-         { echo "$as_me:$LINENO: echo If you wish to use the standard version you must type" >&5
-echo "$as_me: echo If you wish to use the standard version you must type" >&6;}
-         { echo "$as_me:$LINENO: touch noweb" >&5
-echo "$as_me: touch noweb" >&6;}
-         { echo "$as_me:$LINENO: If you wish to use a pre-installed GCL you must type" >&5
-echo "$as_me: If you wish to use a pre-installed GCL you must type" >&6;}
-         { echo "$as_me:$LINENO: make GCLVERSION=gcl-system" >&5
-echo "$as_me: make GCLVERSION=gcl-system" >&6;}
-         ;;
-   esac
-}
-
-if test "x$AXIOM" = "x"; then
-   must_set_AXIOM
-elif test "`dirname $AXIOM`" != "`pwd`/mnt"; then
-   must_set_AXIOM
-else
-   { echo "$as_me:$LINENO: configure complete.  Now type " >&5
-echo "$as_me: configure complete.  Now type " >&6;}
-   { echo "$as_me:$LINENO:                               " >&5
-echo "$as_me:                               " >&6;}
-   { echo "$as_me:$LINENO: make" >&5
-echo "$as_me: make" >&6;}
-fi
-AXIOM=`pwd`/mnt/$SYSNAME
 
 SRCDIRS="bootdir interpdir sharedir algebradir etcdir clefdir docdir \
         graphdir smandir hyperdir inputdir "
@@ -5663,6 +5601,7 @@ s,@axiom_builddir@,$axiom_builddir,;t t
 s,@axiom_build_bindir@,$axiom_build_bindir,;t t
 s,@axiom_build_libdir@,$axiom_build_libdir,;t t
 s,@axiom_targetdir@,$axiom_targetdir,;t t
+s,@MAKE@,$MAKE,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -5675,14 +5614,13 @@ s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
 s,@LN_S@,$LN_S,;t t
+s,@TOUCH@,$TOUCH,;t t
 s,@AWK@,$AWK,;t t
 s,@TAR@,$TAR,;t t
 s,@PATCH@,$PATCH,;t t
-s,@MAKE@,$MAKE,;t t
 s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@AR@,$AR,;t t
-s,@TOUCH@,$TOUCH,;t t
 s,@LATEX@,$LATEX,;t t
 s,@MAKEINDEX@,$MAKEINDEX,;t t
 s,@NOTANGLE@,$NOTANGLE,;t t
